# Generated by Django 4.1 on 2023-01-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
